apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microservice-operator-clusterrole

rules:
  - apiGroups: [imran.dev.io]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]

  - apiGroups: ["", "apps", "batch", "extensions", "networking.istio.io"]
    resources: [namespaces, deployments, pods, services, services/proxy, events, virtualservices, gateway]
    verbs: [list, watch, patch, get, create, delete]

  - apiGroups:
      [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  - apiGroups: [imran.dev.io]
    resources: [microservice, microservices]
    verbs: [list, watch, create, patch, delete, get]
