apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microservice-operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microservice-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: microservice-operator-sa
    namespace: kube-system
