apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microservices.imran.dev.io
spec:
  group: imran.dev.io
  scope: Namespaced
  names:
    plural: microservices
    singular: microservice
    kind: Microservice
    shortNames:
    - ms
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
              affinity:
                type: object
                properties:
                  nodeAffinity:
                    type: object
                    properties:
                      requiredDuringSchedulingIgnoredDuringExecution:
                        type: object
                        properties:
                          nodeSelectorTerms:
                            type: array
                            items:
                              type: object
                              properties:
                                matchExpressions:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                        enum:
                                        - In
                                        - NotIn
                                        - Exists
                                        - DoesNotExist
                                      values:
                                        type: array
                                        items:
                                          type: string
                      preferredDuringSchedulingIgnoredDuringExecution:
                        type: array
                        items:
                          type: object
                          properties:
                            preference:
                              type: object
                              properties:
                                matchExpressions:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                        enum:
                                        - In
                                        - NotIn
                                        - Exists
                                        - DoesNotExist
                                      values:
                                        type: array
                                        items:
                                          type: string
                            weight:
                              type: integer
                              minimum: 1
                              maximum: 100
                  nodeAntiAffinity:
                    type: object
                    properties:
                      requiredDuringSchedulingIgnoredDuringExecution:
                        type: object
                        properties:
                          nodeSelectorTerms:
                            type: array
                            items:
                              type: object
                              properties:
                                matchExpressions:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                        enum:
                                        - In
                                        - NotIn
                                        - Exists
                                        - DoesNotExist
                                      values:
                                        type: array
                                        items:
                                          type: string
                      preferredDuringSchedulingIgnoredDuringExecution:
                        type: array
                        items:
                          type: object
                          properties:
                            preference:
                              type: object
                              properties:
                                matchExpressions:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                        enum:
                                        - In
                                        - NotIn
                                        - Exists
                                        - DoesNotExist
                                      values:
                                        type: array
                                        items:
                                          type: string
                            weight:
                              type: integer
                              minimum: 1
                              maximum: 100
              container:
                type: array
                items:
                  type: object
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                      enum:
                      - Always
                      - IfNotPresent
                      - Never
                    port:
                      type: integer
                      minimum: 1
                      maximum: 65535
                    path:
                      type: string
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                    env:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                          valueFrom:
                            type: object
                            properties:
                              secretKeyRef:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  key:
                                    type: string
                              configMapKeyRef:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  key:
                                    type: string
                    resources:
                      type: object
                      properties:
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
              imagePullSecrets:
                type: array
                items:
                  type: string
            required:
            - replicas
            - image
            - port
          status:
            type: object
            properties:
              ready:
                type: string
    additionalPrinterColumns:
    - name: Replicas
      type: integer
      description: The number of replicas
      jsonPath: .spec.replicas
    - name: Port
      type: integer
      description: The port number
      jsonPath: .spec.port
    - name: Image
      type: string
      description: The image
      jsonPath: .spec.image
    - name: Path
      type: string
      description: The path
      jsonPath: .spec.path
