apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- service-account.yaml
- role.yaml
- rolebinding.yaml
- clusterrole.yaml
- clusterrole-binding.yaml
- deployment.yaml
